name: Generate Metrics

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: Metrics (light)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg
          committer_branch: metrics
          base: header, activity, repositories
          config_timezone: Asia/Kathmandu
          config_theme: light
          plugins_errors_fatal: no

      - name: Metrics (dark)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics-dark.svg
          committer_branch: metrics
          base: header, activity, repositories
          config_timezone: Asia/Kathmandu
          config_theme: dark
          plugins_errors_fatal: no
